sudo: required
language: clojure
jdk:
  - openjdk11
services:
  - docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "HMU9C9BzUN8QSS9I+ZVcHXvEQYFRe0c1AMqqXrej7PYvfm3PniVbYx+IuMWu3mRFqKi8Tz8lCybxXQgPOQZbSJnee2G2QQoGZDPN8QdPNgI9Xmjo40DD4QC4yd10vITbhaxI6b2AOLtZwoFgx7Nrb7m9c9IC+oZoSuZO6maxMRZoc2xZ/3sPOHrw/4FN5V9BKESXsalcysiMtmwfwMEL4VCLtmmXTxn8nmFlBcf40fwWUEuGZgggAiLnzh78tnu7XD8AHbOd98EbRQ8TQCjNrA3H9s1Sp5VefMRKDvqaeKkKQR1i2aR0v390gK3r0vIv6mp6o4ayTTvfvfYVksLtDtx4JmIQ7rPXvdsOuxIx720QupD01/yT2ub4I7/1YgURbZ/hVgtzJdacu0+gUmqfuZrlhyfWC06xKvf0ssae33B96IYDqgCGdIsFFeSoHIZNPmSgMors0a/ict03qBY1NXhez0524YNDF3vggI3aEkyhvUfJPyzlOtey0TjfEhHQVAw2JaLNVO5bqas9dX/uraDLIZ2nFqMDv7pT9Pr8+F9np5Xx5F4FVhN1hwtL9eRWulaTDAwtNf56M57CH6/tTZdFO1EznRtaq/E3a6Tp9ZfaPhN9yUqxkMcGc+Xe0rh1YVm/mIV19A2+/ccvq+3G9YG/Si5dVKmSHTV8zLLncJk="
    # AWS_SECRET_ACCESS_KEY
    - secure: "LrqX5o+y/I9j+v6wj/NhUFh3C6mdDCrZZTAfHekf5NsZJhKKZf69LrvznZJJHb+bR0pLdBuYGxdGg0AQG8eiGJJpW8eNdqQ3kNJ0aZSZ9xFVHtEyK7ReUDejNP/9OQFQ+BygOkwUBlTKkH9EOax65N9eU5vGgYnc/p0bH9/pAeHJpabrUV8LyjHdfVDzzaWFZyGswaxj2lWIwIKM0IkeFEWmnSGa1TmN2uwnFNKWgyOKx8DQvTsC0VJ3iG+iQVDDzbQVMItmCk8qjc/z6r0OyTjthd3dEb8Uoch3N15Ty8jLks/S8MrYr5sUGIm+n/Xke+FyLQuOliW2O1ZtSN+yeqeZAufboASTlik4u+Oqj5ZAxvxOZBj6k+mu2yqv5VC+JI8Q6LwwHVkiCfzvwOLWLTBx7dlUhYYnEuhb2u9F81jZwfG0iXH6a2L9vkSNHl83EBm3OgbaFbnywgxENssMb2WLnIiWT8/525W4uj9IGD6jYuEGiKek3MFDoNluaZPMhV7VhizSCii5F2agLgsY9HhdC0TJ5Iomb8QxPvNFiKEHdF2qeLOHwf+9lV3g2DgqjQHYGanC3zSxyi55Z1wvnDkJ6X84XghuZ6KOKlVg+2yq51O1KewJ4Bbd7paqUbCgwliqy8csOGp6RIy47D5tsRBLQ3yZFK/g0LhYybsUN5A="
    # ARTIFACTORY_USERNAME
    - secure: "KCAYl67PBRavi+hF7gl+TxfuOFI5ivnXisAknNvo26caiAaxw9a5pVpVi3Cp+LpCXRQW5NFO6V6uTjEeJqqMy/oSZKG1YsLxh3U82wznmBL+qMKNQFG8B4ImzIaJEfDzQE7VzKQT0XkoUjMu8iXmUNop5xsvJ6hghcL3CP7vpS1Pm9RnQFzX/7/Sk0+b3qm4tkKZRCtPc3wI6A+uj+C5C0thR1F3zko79dOenpY2z7OKc9zvM8iCZA4o+eap5nB5TEHEEQpK208/gCsHb+zEqG5uXmxiEZk3hl8c0N4SsWJqIiLYG1C9TaWVWBd5pL9koxu67iImZQbsxFk/l6l+qc+XgNV7ogHOCiYljZ3j8HBumDxAoCzLk4j5dyi9GM/nKROOQq1sPDouH8DpgqgMEPubZF7SHkz0IfOjHQ6Scbd3L3cgW01XB8Mdempm0uJjdWyx/CBRffKE5zirIgKFBdFHm3l4iW9QF8TMUJyQCQ0KC2PfWjikZ1kiq3koqMObvPa+JL5UzafLokSMOwzVgMzdJvE3TWRW8yWlU3k0SzO3wyZUVRBj8a7qQwf7rLvpmUHobrC+tjgOyS0mOR2xCj4XMFq5CNG96WntpA6WNf5jGlj0cbg9dvbvZBj1rfdHkMepQ+HXO4/G1OCp6bFOsy9OPO2ueM+EeypfsmBeFao="
    # ARTIFACTORY_PASSWORD
    - secure: "K7JnEVHvwT7xbfc4dcpo0Pm+3SfEg3pwd/JtGSrk7/4yOWJMrZpTNv7v+UlyKtrH5redM/Zfj41pi3hAgTkLfFFkzQSa4XA7pTomLMSMp9jviggLa2aJjIKzMu/DvJLipX1eKUdqlueuwGUB0n+bHL3MKxGoXOx2PFegOPEbHFrZFmXEN2ql1ZJnaePh2VMMBbWCn5sVIf41dx0iE4mnMfw1KEmk9h9cvhy7TdVxXCxIb9ujYcL9+L6dsUYoBK5TLyPfM0JbwcbulUSoyUXzh9XTnx0TO+sMQAfg/QC/1Zs2dUjQaFkKZ9az2qXI/o3kgrQNw+UJWpjJCxzTDZGjOHHtKjhH14qXRGHMfkhBgDuSs660KMD1lusfa3d5BkVumYrQeA8P06qQB0bWdKcuH/hBaT5jF7MO4hrtRpcwCYL9/Xb6jg1TVpfLIi8dW3sQhg4GRKfnNd82tedxrjoXzzbE1Bvcezf7wvf3uuWwaa7ZzxQSZuq2ubuXAnHhafhmAVOXj8bPTPrM3UBTGNwQ3GY/sQq2DS6e4OrG9LPHmr6CSgfFNk7J9H/cXmgCwWhMRii7bYdfnNcsdQyIIi4EwRRsHkIG2PGkd5ThVVoDYhfiHA4AjxhtT/aJqKt7kxkV3J1ZVvB01zBqrBB4NTqRA4QumwI8YPnqLVIN+mYH9DE="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="kouta-indeksoija"

before_script:
  - docker pull localstack/localstack:0.10.2

script:
  - lein -U ci-test
  - lein uberjar

  - mv target/kouta-indeksoija-*-standalone.jar $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk8:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh ${ARTIFACT_NAME}

deploy:
  - provider: script
    script: lein deploy
    skip_cleanup: true
    on:
      branch: OY-3052
  - provider: script
    script: ./ci-tools/build/upload-image.sh ${ARTIFACT_NAME}
    on:
      all_branches: true
