name: Kouta-indeksoija

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Run tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker pull localstack/localstack:0.10.2
          lein -U ci-test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Build
        run: lein uberjar

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  deploy:
    needs: [ test, build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

      - name: Build and deploy Docker containers
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh

          mv target/kouta-indeksoija-*-standalone.jar $DOCKER_BUILD_DIR/artifact/kouta-indeksoija.jar
          cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

          export BASE_IMAGE="baseimage-fatjar-openjdk11:master"

          ./ci-tools/common/pull-image.sh
          ./ci-tools/github-build/build-fatjar.sh kouta-indeksoija
          ./ci-tools/common/clean-docker-build-dir.sh

          ./ci-tools/github-build/upload-image.sh kouta-indeksoija

      - name: Deploy jar-libraries
        if: github.ref == 'refs/heads/master'
        shell: bash
        run: lein deploy