name: Kouta-indeksoija

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Build dev elastic container to use in tests
        run: ./elastic/build.sh

      - name: Run tests
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          docker pull localstack/localstack:3.0.0
          aws --version
          lein -U ci-test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare clojure env
        uses: ./.github/actions/prepare-clojure-env

      - name: Build jar
        run: lein uberjar

      - uses: actions/cache@v4
        id: restore-build
        with:
          path: target
          key: ${{ github.sha }}

  deploy:
    needs: [ test, build ]
    uses: Opetushallitus/.github/.github/workflows/push-scan-java-ecr.yml@main
    with:
      application: kouta-indeksoija
      base-image: baseimage-fatjar-openjdk11:master
      configfolder: oph-configuration
      jarfile: kouta-indeksoija-*-standalone
    secrets:
      AWS_UTILITY_ROLE_ARN: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
