name: dev-elastic-to-ecr

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'elastic/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and tag development elasticsearch docker image
        run: ./elastic/build.sh

      - name: Deploy development elasticsearch docker image to ECR
        run: |
          git clone https://github.com/Opetushallitus/ci-tools.git
          source ci-tools/common/setup-tools.sh
          ./elastic/deploy.sh